### ISSUE TITLE
Implement the accessibility modal

### ISSUE THREAD

**Issue by mindrones** [nestauk/eurito_indicators#36]
See #35

- [x] Various fixes (#41)
- [x] Change the main layout to grid (#42)
- [x] Setup an empty a11y menu (#43)
- [x] Setup the a11y menu navigation (#44)
- [x] Implement radio controls (#45)
- [x] Implement slider controls (#46)
- [x] Implement switch controls (#47)
- [x] Implement resets (#48)
- [x] Hook up text effects (#49)
- [x] Hook up color effects (#50)
- [x] Turn radios into 2 buttons when there's no room enough for labels (#61)

Not to be implemented:
- ~Implement confirmation for resets (#51)~

**Comment by mindrones** [comment]
Done, closing
